--liquibase formatted sql
--changeset carlos.hesketh:001
CREATE TABLE public."person" (
    "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255) NOT NULL,
    CONSTRAINT "pkPerson" PRIMARY KEY ("id")
);
COMMENT ON TABLE public."person" IS 'table person';
COMMENT ON COLUMN public."person"."id" IS 'identity';
COMMENT ON COLUMN public."person"."name" IS 'name of person';